apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: {{ .values.namespace }}
spec:
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: {{ .values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .values.service.type }}